### ISSUE TITLE
throws TypeError

### ISSUE THREAD

**Issue by tommorris** [jlord/offline-issues#21]
When I try to run it on a private repo of mine...

````
Wrote data
Wrote markdown files
/usr/local/lib/node_modules/offline-issues/node_modules/marked/lib/marked.js:1215
    throw e;
          ^
TypeError: Cannot read property 'replace' of null
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/usr/local/lib/node_modules/offline-issues/node_modules/marked/lib/marked.js:137:5)
    at Function.Lexer.lex (/usr/local/lib/node_modules/offline-issues/node_modules/marked/lib/marked.js:128:16)
    at marked (/usr/local/lib/node_modules/offline-issues/node_modules/marked/lib/marked.js:1207:31)
    at parseBody (/usr/local/lib/node_modules/offline-issues/src/writehtml.js:58:16)
    at /usr/local/lib/node_modules/offline-issues/src/writehtml.js:35:13
    at Array.forEach (native)
    at writehtml (/usr/local/lib/node_modules/offline-issues/src/writehtml.js:34:10)
    at /usr/local/lib/node_modules/offline-issues/src/index.js:130:7
    at /usr/local/lib/node_modules/offline-issues/node_modules/cpr/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:90:5
    at FSReqWrap.oncomplete (fs.js:99:15)
````

Works fine on a public repo.

**Comment by cmsj** [comment]
fwiw, I get this on a public repo too (Hammerspoon/hammerspoon)

**Comment by plaindocs** [comment]
Same.

**Comment by jlord** [comment]
I am able to reproduce this using `travis-ci/docs-travis-ci-com` and will look into it today 👍
