### ISSUE TITLE
Doesn't work on Windows 8

### ISSUE THREAD

**Issue by garncarz** [jlord/offline-issues#25]
It doesn't wait for me to type the password... ends with

```
[Error: {"message":"Bad credentials","documentation_url":"https://developer.gith
ub.com/v3"}]
C:\Users\Ondra\AppData\Roaming\npm\node_modules\offline-issues\src\index.js:15
  headers["Authorization"] = 'token ' + token.token
                                             ^

TypeError: Cannot read property 'token' of undefined
    at module.exports (C:\Users\Ondra\AppData\Roaming\npm\node_modules\offline-i
ssues\src\index.js:15:46)
    at C:\Users\Ondra\AppData\Roaming\npm\node_modules\offline-issues\src\cli.js
:38:3
    at C:\Users\Ondra\AppData\Roaming\npm\node_modules\offline-issues\node_modul
es\ghauth\ghauth.js:114:16
    at BufferList._callback (C:\Users\Ondra\AppData\Roaming\npm\node_modules\off
line-issues\node_modules\ghauth\ghauth.js:37:14)
    at BufferList.end (C:\Users\Ondra\AppData\Roaming\npm\node_modules\offline-i
ssues\node_modules\ghauth\node_modules\bl\bl.js:75:10)
    at Stream.onend (stream.js:59:10)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at Stream.handleEnd (C:\Users\Ondra\AppData\Roaming\npm\node_modules\offline
-issues\node_modules\ghauth\node_modules\hyperquest\node_modules\duplexer\index.
js:81:21)
    at emitNone (events.js:72:20)
```

But works when run under Mintty (Cygwin's terminal).

**Comment by lorinkoz** [comment]
Not working for me on Windows 7 32 bits, neither through Cygwin nor `cmd`.

**Comment by jlord** [comment]
Hmm, I'm only able to test on Windows 8.1 and it worked. I'm not familiar with the differences between that, Windows 8 and Windows 7 32 to have much of an idea right now about why it would be skipping through the auth steps.

I've updated the auth dependency and if either of you could give it a try either from `master` or later today when I've published a new version that would be awesome.

**Comment by garncarz** [comment]
By that Windows 8 I meant Windows 8.1, sorry I wasn't exact enough.

I'll try it, but I'm not familiar with npm, what should I change `npm install -g offline-issues` to to work with `master`?

**Comment by garncarz** [comment]
Oh, it was 2 days old comment... so under Cygwin I've tried `npm install -g offline-issues` and then `offline-issues`, it asked for password which was visible when typed. Then `offline-issues USER/REPO` and it worked.

When I retried `offline-issues` under `cmd.exe`, it didn't ask for password again. I don't exactly like the idea of storing my password somewhere in plain text. Couldn't the program ask for it everytime it's being executed, please?
