### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by benbalter** [jlord/offline-issues#29]
👋 `@jlord`! Big net promoter of offline-issues. It seems I recently started receiving the following error:

```
$ offline-issues benbalter/benbalter.github.com
Wrote data.
Wrote markdown files.
Wrote html files.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at copy (/usr/local/lib/node_modules/offline-issues/node_modules/cpr/lib/index.js:136:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This appeared immediately after logging in with 2FA and attempting to clone down the issues for my public, personal site (`benbalter/benbalter.github.com`). 

I swear I read the directions (and things had been working great for a while). Using `v0.1.0`.

This occurs if I use the global `offline-issues` bin, or if I invoke `./node_modules/.bin/offline-issues` directly from my project. Halp?

**Comment by jlord** [comment]
Hmm, ok I just cloned the project fresh on a newish computer and `npm` linked it and ran it on a couple of repositories and it worked. I'll dig around some more and try and see what's up.

**Comment by jlord** [comment]
I ended up getting this error when I was testing the module on Ubuntu. I tracked it down to being because `cpr` didn't know to overwrite files that were duplicates when `offline-issues` was run twice in the same dir.

@benbalter if you could update your dependency or clone and install `master` and then `npm link` and let me know if things are better now?

**Comment by benbalter** [comment]
> was run twice in the same dir.

Ahh, that sounds like my problem. Not urgent. Will wait for the NPM fix. Thanks for looking into this! :smile:
