### ISSUE TITLE
Can't login with 2FA/OTP

### ISSUE THREAD

**Issue by searls** [jlord/offline-issues#35]
Logging in doesn't work for me, unfortunately:

```
Your GitHub OTP/2FA Code (optional): 985184
{ [Error: Must specify two-factor authentication OTP code.]
  data: 
   { message: 'Must specify two-factor authentication OTP code.',
     documentation_url: 'https://developer.github.com/v3/auth#working-with-two-factor-authentication' } }
/Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/src/index.js:17
  headers['Authorization'] = 'token ' + token.token
                                             ^

TypeError: Cannot read property 'token' of undefined
    at module.exports (/Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/src/index.js:17:46)
    at /Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/src/cli.js:35:3
    at afterCreateAuth (/Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/node_modules/ghauth/ghauth.js:155:16)
    at BufferList.afterCreateAuthResponse [as _callback] (/Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/node_modules/ghauth/ghauth.js:42:14)
    at BufferList.end (/Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/node_modules/ghauth/node_modules/bl/bl.js:98:10)
    at DuplexWrapper.onend (/Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/node_modules/ghauth/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DuplexWrapper.emit (events.js:166:7)
    at /Users/justin/.nodenv/versions/4.4.1/lib/node_modules/offline-issues/node_modules/ghauth/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:934:16
```

**Comment by techgithub345** [comment]
You must specify the two-factor authentication OTP code for that to work.

**Comment by Jolg42** [comment]
Working for me with latest version. I think this issue can be closed now.
