### ISSUE TITLE
TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by snowman** [jlord/offline-issues#55]
```
Your GitHub username: 123@mail.com
Your GitHub password: ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔

(node:120349) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
{ Error: connect ECONNREFUSED 13.250.168.23:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.250.168.23',
  port: 443 }
$HOME/.nvm/versions/node/v10.18.0/lib/node_modules/offline-issues/src/index.js:17
  headers['Authorization'] = 'token ' + token.token
                                              ^

TypeError: Cannot read property 'token' of undefined
    at module.exports ($HOME/.nvm/versions/node/v10.18.0/lib/node_modules/offline-issues/src/index.js:17:47)
    at $HOME/.nvm/versions/node/v10.18.0/lib/node_modules/offline-issues/src/cli.js:35:3
    at afterPrompt ($HOME/.nvm/versions/node/v10.18.0/lib/node_modules/offline-issues/node_modules/ghauth/ghauth.js:149:14)
    at DuplexWrapper.after2FaResponse ($HOME/.nvm/versions/node/v10.18.0/lib/node_modules/offline-issues/node_modules/ghauth/ghauth.js:99:14)
    at DuplexWrapper.emit (events.js:198:13)
    at ClientRequest.<anonymous> ($HOME/.nvm/versions/node/v10.18.0/lib/node_modules/offline-issues/node_modules/hyperquest/index.js:13:19)
    at ClientRequest.emit (events.js:203:15)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
```

**Comment by Saurabh1901** [comment]
Can I work on this?
